"""initial migration

Revision ID: 1b5a46230e57
Revises: 
Create Date: 2018-05-16 19:10:24.546380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5a46230e57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_db',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('user_password', sa.String(length=20), nullable=True),
    sa.Column('user_phone', sa.String(length=20), nullable=True),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('user_card', sa.String(length=20), nullable=True),
    sa.Column('user_role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_db')
    # ### end Alembic commands ###
